version: '3.8'
services:
  geth:
    image: ethereum/client-go:stable
    command: >
      --sepolia
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --http.api eth,net,web3,engine
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8546
      --authrpc.vhosts=localhost
      --authrpc.jwtsecret=/jwt/jwt.hex
      --authrpc.addr 0.0.0.0
      --authrpc.port 8551
      --metrics
      --metrics.addr 0.0.0.0
      --metrics.port 6060
      --datadir /data
    volumes:
      - ./data:/data
      - ../jwt:/jwt
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
      - "6060:6060"
    restart: unless-stopped

  beacon:
    image: gcr.io/prysmlabs/prysm-beacon:stable
    command: >
      --sepolia
      --datadir=/data
      --execution-endpoint=http://geth:8551
      --jwt-secret=/jwt/jwt.hex
      --checkpoint-sync-url=https://sepolia.checkpoint-sync.ethdevops.io
      --genesis-beacon-api-url=https://sepolia.checkpoint-sync.ethdevops.io
      --http-web3provider=http://geth:8545
      --accept-terms-of-use
      --rpc-host=0.0.0.0
      --rpc-port=4000
      --grpc-gateway-host=0.0.0.0
      --grpc-gateway-port=3500
      --p2p-tcp-port=13000
      --p2p-udp-port=12000
      --monitoring-host=0.0.0.0
      --monitoring-port=8080
    volumes:
      - ./data:/data
      - ../jwt:/jwt
    ports:
      - "4000:4000"
      - "3500:3500"
      - "13000:13000"
      - "12000:12000/udp"
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - geth 